### ISSUE TITLE
traQへ認証のために遷移しようとするとエラーになる

### ISSUE THREAD

**Issue by kaitoyama** [traPtitech/anke-to#1083]
New Questionnaireを押して、traQに移動しますのポップアップを押すと発生する。
0cd82c5a3ad3638275bd33977b3d435909973c75に関連していそうです。
dev環境で出たエラーは以下の通りです。
```
Buffer is not defined
ReferenceError: Buffer is not defined
    at encode (webpack-internal:///./node_modules/base64url/dist/base64url.js:6:5)
    at getCodeChallenge (webpack-internal:///./src/bin/traqAuth.js:163:59)
    at sendCodeRequest (webpack-internal:///./src/bin/traqAuth.js:169:23)
    at _callee2$ (webpack-internal:///./src/router/index.js:190:81)
    at tryCatch (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:87:17)
    at Generator.eval (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:171:22)
    at Generator.eval [as next] (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:112:21)
    at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:9:24)
    at _next (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:28:9)
```

**Comment by kaitoyama** [comment]
原因は確定で 0cd82c5a3ad3638275bd33977b3d435909973c75 のようです。(その前のcommitでは正常に動きました。)
このissueに関係していそうです。
https://github.com/brianloveswords/base64url/issues/33

**Comment by kaitoyama** [comment]
@cp-20 
解決方法わかります?

**Comment by kaitoyama** [comment]
最新コミットです。
自分の手元ではmake dev動いてます。
エラーメッセージもらえますか?

**Comment by cp-20** [comment]
コミットハッシュは https://github.com/traPtitech/anke-to/commit/513ebe892bf2d8eb1122e5d0dab1cd6abda43028 でした。

```
docker-compose -f docker/dev/docker-compose.yaml up --build
#1 [anke-to internal] load build definition from Dockerfile
#1 transferring dockerfile: 709B done
#1 DONE 0.0s

#2 [anke-to internal] load .dockerignore
#2 transferring context: 131B done
#2 DONE 0.0s

#3 [anke-to internal] load metadata for docker.io/library/golang:1.20.7-alpine
#3 DONE 3.1s

#4 [anke-to 1/7] FROM docker.io/library/golang:1.20.7-alpine@sha256:03278bc16e1a5b4fb6cdd3462108c060aa1e9c2353ce4d15d744b3c40168677d
#4 DONE 0.0s

#5 [anke-to internal] load build context
#5 transferring context: 55B done
#5 DONE 0.0s

#6 [anke-to 4/7] RUN go install github.com/cosmtrek/air@v1.27.3
#6 CACHED

#7 [anke-to 5/7] COPY go.mod go.sum ./
#7 CACHED

#8 [anke-to 2/7] RUN apk add --update --no-cache ca-certificates git
#8 CACHED

#9 [anke-to 6/7] RUN go mod download
#9 CACHED

#10 [anke-to 3/7] WORKDIR /go/src/github.com/traPtitech/anke-to
#10 CACHED

#11 [anke-to 7/7] RUN apk add --no-cache openssl  && wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-alpine-linux-amd64-v0.6.1.tar.gz  && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-v0.6.1.tar.gz  && rm dockerize-alpine-linux-amd64-v0.6.1.tar.gz
#11 CACHED

#12 [anke-to] exporting to image
#12 exporting layers done
#12 writing image sha256:1740f130021ff0f20a4e7789528a9fa19e91c7ca715aebc0ce9c79b399fcebed done
#12 naming to docker.io/library/dev-anke-to done
#12 DONE 0.0s
Attaching to dev-anke-to-1, dev-mysql-1
dev-anke-to-1  | 
dev-anke-to-1  |   __    _   ___  
dev-anke-to-1  |  / /\  | | | |_) 
dev-anke-to-1  | /_/--\ |_| |_| \_ , built with Go 
dev-anke-to-1  | 
dev-anke-to-1  | [16:53:34] mkdir /go/src/github.com/traPtitech/anke-to/tmp
dev-anke-to-1  | [16:53:34] watching .
dev-anke-to-1  | [16:53:34] !exclude client
dev-anke-to-1  | [16:53:34] watching docker
dev-anke-to-1  | [16:53:34] watching docker/dev
dev-anke-to-1  | [16:53:34] watching docker/staging
dev-anke-to-1  | [16:53:34] watching docker/test
dev-anke-to-1  | [16:53:34] watching docker/tuning
dev-anke-to-1  | [16:53:34] watching docs
dev-anke-to-1  | [16:53:34] watching docs/swagger
dev-anke-to-1  | [16:53:34] watching model
dev-anke-to-1  | [16:53:34] watching router
dev-anke-to-1  | [16:53:34] !exclude tmp
dev-anke-to-1  | [16:53:34] watching traq
dev-anke-to-1  | [16:53:34] !exclude tuning
dev-anke-to-1  | [16:53:34] building...
dev-anke-to-1  | error obtaining VCS status: exit status 128
dev-anke-to-1  | 	Use -buildvcs=false to disable VCS stamping.
dev-anke-to-1  | [16:53:34] failed to build, error: exit status 1
```

**Comment by xxarupakaxx** [comment]
確かportalとかで同じエラーを見た気がする
探してみる

**Comment by xxarupakaxx** [comment]
これかな？

https://github.com/traPtitech/portal/pull/150

**Comment by kaitoyama** [comment]
@cp-20 
↑お願いします

**Comment by cp-20** [comment]
再現しました！感謝

**Comment by cp-20** [comment]
BufferはNode.jsから提供されているクラスっぽいので、それをブラウザ側で呼んでることがエラーの原因っぽいですね

**Comment by cp-20** [comment]
https://github.com/feross/buffer を使って`src/bin/traqAuth.js`を

```diff
  import axios from 'axios'
  import sha256 from 'js-sha256'
+ window.Buffer = require('buffer/').Buffer
  import base64url from 'base64url'
```

みたいに書き換えたら件のエラーはなくなりました。ただまた別のエラーが発生するようになりました

```
Redirected when going from "/targeted" to "/questionnaires/new" via a navigation guard.
    at createRouterError (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2056:15)
    at createNavigationRedirectedError (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2015:10)
    at eval (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2386:17)
    at _callee2$ (webpack-internal:///./src/router/index.js:198:13)
    at tryCatch (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:87:17)
    at Generator.eval (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:171:22)
    at Generator.eval [as next] (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:112:21)
    at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:9:24)
    at _next (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:28:9)
```

**Comment by cp-20** [comment]
ただ`base64url`自体があんまり大きいライブラリではないので、わざわざ新しいライブラリを使って強引に動かすようリハこれを`Buffer`を使わずにrewriteするのが良さそうです。

ref: base64urlの実装 https://github.com/brianloveswords/base64url/blob/master/src/base64url.ts
ref: ブラウザでのbase64変換 https://qiita.com/i15fujimura1s/items/6fa5d16b1e53f04f3b06

**Comment by cp-20** [comment]
さらに言えば、encodeしか使ってないのでかなり実装は軽そうです

**Comment by kaitoyama** [comment]
実装フロント側でお願いしていいですか？

**Comment by cp-20** [comment]
分かりました　たださっきちょこちょこいじってた感じはNode.jsのBufferを使ったときと別の方法でやったときの結果が合わないみたいなことが合ったので、あまりすぐにはできないかもです

**Comment by cp-20** [comment]
↑たぶん直りました

**Comment by cp-20** [comment]
> https://github.com/feross/buffer を使って`src/bin/traqAuth.js`を
> 
> ```diff
>   import axios from 'axios'
>   import sha256 from 'js-sha256'
> + window.Buffer = require('buffer/').Buffer
>   import base64url from 'base64url'
> ```
> 
> みたいに書き換えたら件のエラーはなくなりました。ただまた別のエラーが発生するようになりました
> 
> ```
> Redirected when going from "/targeted" to "/questionnaires/new" via a navigation guard.
>     at createRouterError (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2056:15)
>     at createNavigationRedirectedError (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2015:10)
>     at eval (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2386:17)
>     at _callee2$ (webpack-internal:///./src/router/index.js:198:13)
>     at tryCatch (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:87:17)
>     at Generator.eval (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:171:22)
>     at Generator.eval [as next] (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:112:21)
>     at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:9:24)
>     at _next (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:28:9)
> ```

ただこのエラーは解決してないです

**Comment by kaitoyama** [comment]
認証への遷移、できるようになったのを確認しました!
ありがとうございます。
引き続き↑のエラーの対応お願いします。

**Comment by cp-20** [comment]
エラーとしては問題ないと思うのでとりあえず`catch`して放置することで解決(?)できました
